# .github/workflows/build.yml
name: Update SVG

on: 
  repository_dispatch:
  
permissions:
  contents: write
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the binary
        run: |
          ls -al
          chmod +x ishowoff_github
          ./ishowoff_github ${{ github.event.client_payload.arguments }}
          
      - name: Commit report
        run: |
          git config --global user.name 'IShowOff'
          git config --global user.email 'ishowoff@showingoff.com'
          git commit -am "Updating session"
          git push
